obd/elm327.py, obd/obd.py
ELM327 only
I overcame the Py3 problems against obdsim with some minor changes to the __read and __write methods. I also made baudrate configurable in this class to use as a starting point for making it configurable elsewhere (my reader isn't operating at 38.4, so I need this), and changed the checks for "OK" to use a common function rather than repeating similar code over and over. 
I strongly recommend changing __read to return a list of sanitized strings (like the way my __isok method does) rather than relying on your current strip method (I think the strip method is contributing to issue #13). I think it will make interpreting the data a lot easier later on.
=> more tweaks for python v3, plus some suggestions for the future

obd/protocols/protocol_can.py
I've noticed many invalid returns from can of size 19 when padded with the additional 5 zeros. This crashes the watcher thread. This will handle them as unhexlify dumps
=> Handle odd sized returns

docs/Connections.md, obd/async.py, obd/elm327.py, obd/obd.py
Why:
* the hard-coded value of 0.1 was making it impossible to connect with
OSX, and possibly in other cases. -- https://github.com/brendan-w/python-OBD/issues/58
This change addresses the need by:
* Adding `conn_timeout` kwarg to OBD and Async, which defaults to 0.1,
but can be configured to suit the user's neeeds.
Other observations:
* There were a few failing tests locally (python3.6 on OSX 10.12.6) when
I cloned the repo, these tests are still failing.  I may look into these
next and submit another PR.
=> Make connection timeout configurable

obd/elm327.py
Solves issue #107 by using pyserial's API. It is then also possible to use "socket://" type of URL's. Works on my elm327 over wifi and shouldn't break the current usage.
=> Changed line to use pyserial's "serial_for_url" instead of "Serial" for compatibility

docs/Async Connections.md, obd/asynchronous.py, obd/elm327.py
Manage connection drop while Async is active without throwing an
exception.
Add delay_cmds argument to Async.
Revised documentation.
=> Better Async management

docs/Connections.md, obd/asynchronous.py, obd/elm327.py, obd/obd.py
Add support for entering low power mode. By sending a ATLP command we can tell the ELM327 to enter low power mode. We also add support for leaving low power mode by sending a space.
=> Add support for the ELM327 Low Power mode

obd/asynchronous.py
**Fix obd.Async() exception when failing to open the serial device.**
Fixed exception:
*AttributeError: 'Async' object has no attribute '_Async__thread'*
Fixes https://github.com/brendan-w/python-OBD/issues/67
Testing program:
```
import obd
import sys
connection = obd.Async(sys.argv[1])
```
**Before the patch:**
- No exception:
`python3 test-async.py /dev/existing-device`
- Exception:
`python3 test-async.py /dev/unexisting-device`
AttributeError: 'Async' object has no attribute '_Async__thread'
**After the patch:**
- `python3 test-async.py /dev/existing-device`
no exception
- `python3 test-async.py /dev/unexisting-device`
[obd.elm327] [Errno 2] could not open port /dev/unexisting-device:
[Errno 2] No such file or directory: '/dev/unexisting-device'
[obd.obd] Cannot load commands: No …
=> Avoiding Async exception on serial port failure

obd/OBDCommand.py
Better representation of a container of `OBDCommand`s.
```python
>>> obd.commands.base_commands()
[<obd.OBDCommand.OBDCommand object at 0x7f3945cb7160>, <obd.OBDCommand.OBDCommand object at 0x7f393835f3c8>, <obd.OBDCommand.OBDCommand object at 0x7f3938361d68>, <obd.OBDCommand.OBDCommand object at 0x7f393835f390>, <obd.OBDCommand.OBDCommand object at 0x7f3938349748>, <obd.OBDCommand.OBDCommand object at 0x7f3938349780>, <obd.OBDCommand.OBDCommand object at 0x7f39383497b8>]
```
```python
>>> obd.commands.base_commands()
[OBDCommand(PIDS_A, b'0100'), OBDCommand(MIDS_A, b'0600'), OBDCommand(GET_DTC, b'03'), OBDCommand(CLEAR_DTC, b'04'), OBDCommand(GET_CURRENT_DTC, b'07'), OBDCommand(ELM_VERSION, b'ATI'), OBDCommand(ELM_VOLTAGE, b'ATRV')]
>>> print("\n".join(map(repr, …
```
=> Add __repr__ to OBDCommand

tests/test_OBD.py
It should be 'bytes' type and not string.
=> Fix 'toy command' class type used for testing

obd/OBDCommand.py
This is a small enhancement to *`__repr__`* to produce a working function. Notice anyway that the decoding function is fixed to `raw_string` and needs `from obd.decoders import raw_string` to be tested.
Test program:
```
import obd
from obd import OBDCommand, Unit
from obd.protocols import ECU
from obd.decoders import raw_string
def ABC(messages): # integer value of the first, second and third byte
try:
return(int("\n".join([n.raw() for n in messages])[9:15], 16))
except:
return None
odo = OBDCommand(
"Odometer",
"Total Distance Traveled",
b"2128",
5,
lambda m: None if ABC(m) == None else Unit.Quantity(ABC(m), Unit.kilometer),
ECU.ALL,
True,
header=b'7E2'
)
```
Output:
--------
**Before:**
```
>>> odo
OBDCommand(Odometer, b'2128')
>>> obd.commands.SPEED
OBDCommand(SPEED, b'010D')
``` …
=> revise __repr__ to produce a working function

obd/OBDCommand.py
Adding actual size and expected size of response error messages in case of wrong size.
This helps checking the size of custom PIDs (e.g., 4th parameter of `OBDCommand`).
**Example 1**
In the following custom command, the right size should be 8.
```
shift_l = OBDCommand(
"Shift_J",
"Shift Joystick",
b"2141",
7, # instead of 8
Shift_J,
ECU.ALL,
True,
header=b'7E2'
)
```
Before:
[obd.OBDCommand] Message was longer than expected. Trimmed message: bytearray(b'aA\xc5\xc6\xb5\xb28')
After:
[obd.OBDCommand] Message was longer than expected **(8>7)**. Trimmed message: bytearray(b'aA\xc5\xc6\xb5\xb28')
**Example 2**
```
shift_l = OBDCommand(
"Shift_J",
"Shift Joystick",
b"2141",
9, # instead of 8
Shift_J,
ECU.ALL,
True,
header=b'7E2'
)
```
Before:
[obd.OBDCommand] Message was shorter than expected. …
=> Better message size error

docs/Connections.md
While the documentation had no quotes, the code needed the quotes. Passing obd.Async(port, protocol="3") is the correct way not obd.Async(port, protocol=3). While this is evident from reading the code, this change makes is more evident.
=> Minor change to the protocol values

obd/elm327.py
This corrects the following issue, detected on a Raspberry Pi connecting via Bluetooth (though it may not be exclusive to this case): https://github.com/brendan-w/python-OBD/issues/160
The root cause was that the `send` command was attempting to retrieve responses from the OBD adapter before they were available for the startup commands (likely due to latency over Bluetooth or some slowness with the dongle itself). I verified that each of `ATH1`, `ATL0`, and `AT RV` would not work on my Raspberry Pi 4 with bluetooth without using at least a 0.1 second delay. 
My first thought was to use the `fast=False` configuration value to add a delay to `__send()`, but on experimentation I discovered that this created an artificial delay which was unnecessary for retrieving values later (such as …
=> Fix send delay for bluetooth/Raspberry Pi

obd/elm327.py
This is just a quick fix to the error message logged when an invalid ELM327 proto is requested. Tested in py27.
=> Patch invalid protocol error message.

README.md, docs/Command Tables.md, obd/commands.py, obd/decoders.py, tests/test_decoders.py
This is baed on the original work by Paul Mundt
(https://github.com/brendan-w/python-OBD/pull/151).
This patch includes adding a simple git test case.
This will finally fix: https://github.com/brendan-w/python-OBD/issues/42
Signed-off-by: Alistair Francis <alistair@alistair23.me>
=> Add support for Mode 9 PIDS

.travis.yml, tox.ini
Drop testing for Python2 as it's unsupported. Let's also add tests for Python 3.8.
=> travis: Update the Python versions

obd/protocols/protocol.py
When using OBD over legacy protocols like K-line the
message is rejected because the ecu id is undefined
even if the data is retrieved correctly.
Add the ENGINE ID and TRANSMISSION ID to the list of ecu
map at object creation time to have it available when
receiving the message.
Data is retrieved correctly on K-Line. Car used VW Lupo GTI
Data is retrieved correctly on CAN cars. Car used Ford Focus.
Signed-off-by: Catalin Ghenea <catalin.ghenea@gmail.com>
=> Fix ECU ID for legacy protocol

obd/elm327.py
Increase "0100" query (PIDS_A) timeout to support inexpensive/slow OBDII adapters.
This patch fixes the case in which "SEARCHING" is not shown after "0100",
due to slow response of cheap devices.
```
[obd.elm327] write: '0100\r'
[obd.elm327] read: b'SEARCHING...\r...
```
It should also fix the case in which the debug mode needs to be active:
in fact the debug logs might slow down the query timeout enough to be able
to catch the query answer.
Reference #205
Reference #200
Reference #187
=> Support slow OBD adapters

obd/elm327.py
Can't auto detect protocol on BT connection
even if the elm devices detects the protocol
successfully.
Add delay after erasing stored protocols
so the adapter can read the discover command
Tested on an Mazda MX5.
The protocol can be detected successfully
on each run. Tested for about 10 times in a row.
Signed-off-by: Catalin Ghenea <catalin.ghenea@gmail.com>
=> Fix protocol auto detect on BT Elm 327

tests/test_protocol.py
Originally, the ECU map was empty up on protocol initialization
https://github.com/brendan-w/python-OBD/blob/2c7828ebd103da4fe20b3292b5595a07b214b061/obd/protocols/protocol.py#L117
For some reason, tests checked the opposite and were "fixed" by @brendan-w in https://github.com/brendan-w/python-OBD/commit/2c7828ebd103da4fe20b3292b5595a07b214b061.
In 2020, @gmaniak authored https://github.com/brendan-w/python-OBD/commit/c14db6a3f13c3b0cf43dc6701d146cc92b08e5eb where they fixed an issue with ECU ID for legacy protocols by filling out the ECU map. This change broke the `test_populate_ecu_map` test which expected the map to be empty.
I am not an OBD/CAN expert, but looking at the above changes it seems that the @gmaniak change is valid, and the map must not be empty. I updated the test so that …
=> Fix test_populate_ecu_map test

obd/elm327.py
Right now __read() will stop reading at "OK" even if a ">" is still coming.
This can cause the ">" to be seen as the response to the next command, which
confuses the initialization sequence, since the initialization sequence
expects a very specific set of responses to its commands.
This changes __read() so that by default it only treats ">" as the response
terminator. When we issue the "ATLP" command to enter low-power mode, we will
use "OK" as the response terminator instead, since that's the only time we
don't expect to see a prompt.
This should fix #226 and should also fix #227.
=> Fix ELM327 synchronization on startup

setup.py
python-OBD does not work with python 3.9+ because the old `pint` version uses deprecated collections API:
```python
ImportError: cannot import name 'MutableMapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
```
The issue was fixed in a newer `pint`.
This change, however, sets the minimum supported python version to 3.8, according to pint's README.
=> Python 3.9+ support

.github/workflows/ci.yml, tox.ini
pint=0.19.* is not available for python versions lower 3.8.
Updated the python version matrix used in CI to 3.8,3.9,3.10.
Also, updated `pytest` and `pytest-cov` versions as the older versions weren't compatible with py3.10.
=> Update the python version range to 3.8-3.10

docs/index.md
Several punctuation fixes. Also included caveat regarding which OBD this will work with (which is necessary because some people might interpret that it will work on OBD-I otherwise).
=> Included note mentioning which OBD it will work with.
